### ISSUE TITLE
Compile error in Angular 9

### ISSUE THREAD

**Issue by saminmel** [kuhnroyal/mat-datetimepicker#85]
It fails to compile with Angular 9. 

`ERROR in Failed to compile entry-point @mat-datetimepicker/core (module as esm5) due to compilation errors:
node_modules/@mat-datetimepicker/core/fesm5/mat-datetimepicker-core.js:820:30 - error NG1010: Value at position 0 in the NgModule.imports of NativeDatetimeModule is not a reference: [object Object]

820                     imports: [NativeDateModule],
                                 ~~~~~~~~~~~~~~~~~~
node_modules/@mat-datetimepicker/core/fesm5/mat-datetimepicker-core.js:837:30 - error NG1010: Value at position 1 in the NgModule.imports of MatNativeDatetimeModule is not a reference: [object Object]

837                     imports: [
                                 ~
838                         NativeDatetimeModule,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
839                         MatNativeDateModule
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
840                     ],
    ~~~~~~~~~~~~~~~~~~~~~
node_modules/@mat-datetimepicker/core/fesm5/mat-datetimepicker-core.js:3927:30 - error NG1010: Value at position 1 in the NgModule.imports 
of MatDatetimepickerModule is not a reference: [object Object]

3927                     imports: [
                                  ~
3928                         CommonModule,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ...
3933                         A11yModule
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3934                     ],`

**Comment by DenysVuika** [comment]
Having same issue when migrating from Angular 8 to 9 today. I really hope this can be solved easily.

**Comment by bbortt** [comment]
Test it using a compiled version from #84 .

**Comment by m0t0r** [comment]
@saminmel the released 4.0.0 version should solve these issues. Please try it and close the issue if everything works for you.

**Comment by bbortt** [comment]
closing this as we are on angular release 13 since `v8.0.0` (even being on `^9.0.0` since yesterday [refactoring]).
